<?php 
	// Provincies
	$provincies = array(

					"drenthe" => array(

						'name' 	=> 	"Drenthe",
						'title' 	=> 	"Dating Drenthe",
						'info' 	=>	"De mooiste singles vind je in Drenthe. Van gratis daten in Assen tot gratis daten in Emmen, overal in Drenthe zijn afspraakjes te regelen. Wil je spannend contact of gewoon een gezellige gratis date? Zoek dan snel naar iemand die aan jouw wensen voldoet. Zoek tussen alle contactadvertenties van Drenthe naar jouw droomvrouw.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Drenthe?</h3><hr><p>Na je date gevonden te hebben tussen de contactadvertenties Drenthe, kan jij jouw toekomstige date aanspreken en kijken of er interesse is. Als jullie beiden geïnteresseerd zijn in elkaar komt het moment om een date te plannen. Jullie bespreken een datum af en jij mag haar verrassen met een leuke activiteit. Misschien heb jij totaal geen idee waar je haar mee naartoe zal nemen op zo’n eerste date. Daten in Drenthe is makkelijker dan je zou denken. Er is genoeg te bekijken en te doen op een date in Drenthe. Met deze dating tips ben je verzekerd van een super gezellige date met je droomvrouw.</p><h4>Waar kan jij het beste daten in Drenthe</h4><p>Als jullie beide sportief zijn, dan is het zeker aan te raden jouw date mee te nemen naar <a href='https://joytime.nl/klimpark-grolloo/' target='_blank'>Outdoor Grollo klimpark</a>. Breng je spannende date naar ongekende hoogte in het outdoor klimbos. Leg daar de verschillende parcoursen af die tussen de 2 en 10 meter hoog zijn, overwin samen meer dan 70 hindernissen en verschillende kabelbanen. Jullie zullen beide een bijzondere belevenis hebben in de hoogte van de boomtoppen. Toch niet zo’n actieve date, maar willen jullie het rustig houden de eerste keer? Neem je date mee naar het historische dorpje <a href='https://orvelte.net/' target='_blank'>Orvelte</a>. Orvelte is een prachtig dorp voor een leuk uitje en om elkaar beter te leren kennen. Onder het genot van een wandeling kan je monumentale boerderijen bezoeken en er zijn bijzonder mooie tuinen te bezichtigen. Jij kan jouw date verzekeren van een heerlijke rustige dag en samen een stukje geschiedenis opsteken. Staan je activiteiten er toch niet bij en wil je liever iets anders doen? Zoek op dating Drenthe voor andere leuke activiteiten.</p><h4>Dating Drenthe</h4><p>Kortom meer dan 10.000 vrijgezellen staan tussen de  contactadvertenties Drenthe. Deze vrijgezellen zijn al lang alleen en willen graag eens meegenomen worden op een date in Drenthe om het beter te leren kennen. Vraag je aanstaande date mee om eens gezellig de stad te bezoeken, of misschien wil je haar wel meenemen buiten de stad? Ook daar is genoeg te bezoeken om jouw date tot een succes te maken. Dating Drenthe heeft genoeg opties om je liefdesleven een nieuwe impuls te geven.</p>",
						'img' 	=>	"drenthe"
						),
					"flevoland" => array(

						'name' 	=> 	"Flevoland",
						'title' 	=> 	"Dating Flevoland",
						'info' 	=>	"Flevoland is niet alleen de jongste provincie van ons land, maar ook de provincie met veel singles die bijvoobeeld willen daten in Almere. Deze singles zoeken een afspraakje en willen graag snel en gratis daten. Heb je al een mooie jonge dame gevonden die bij je past? Zoek snel tussen de contactadvertenties van Flevoland of er nog een single is die openstaat voor gezellige afspraakjes!",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Flevoland?</h3><hr><p>Na een tijdje leuke berichten over en weer gewisseld te hebben met je nieuwe liefde, wil je toch graag eens een leuke date. Die date moet zeker voor herhaling vatbaar zijn en daarom hebben we hier een aantal tips. Met deze dating tips ben je verzekerd van een geslaagde dag als jij jouw date daar naartoe neemt. In Flevoland kan je op allerlei plekjes terecht voor een leuke date.</p><h4>Waar kan je het beste daten in Flevoland</h4><p>Ontdek bijvoorbeeld Schokland of bezoek de Batavia werf, loop tezamen op het blote voeten zeebodempad of misschien wel een bezoek aan Aviodrome. Ook de Oostvaardersplassen is een mooie plek om je date mee naartoe te nemen. Ontdek samen met jouw date het verborgen verleden van <a href='https://schokland.nl/' target='_blank'>Werelderfgoed Schokland</a>, maak gelijk een wandeling en ontdek de historie van het archeologisch monument vol met bodemschatten. Verder kunnen jullie leren om samen zeemansliedjes te zingen. Wat ook kan is met elkaar een fiets huren en elkaar een fijne dag te bezorgen in de natuur. Altijd al eens willen kijken in <a href='https://www.batavialand.nl/' target='_blank'>Batavialand</a>? Hier staat het VOC-schip compleet gereconstrueerd en is de exacte replica van de echte Batavia die in 1628 gebouwd werd. Hier kan je met jouw date terug in de tijd en ontdekken hoe het was om 350 jaar geleden de zeeën te trotseren.</p><h4>Dating Flevoland</h4><p>Wil je toch wat anders? In Flevoland zijn meer dan 10.000 singles nog steeds op zoek zijn en hier staan met een contactadvertentie. Zij dromen van een man die ze meeneemt langs ongekende plekken. Dan kan je altijd de natuur op zoeken en je vrouw meenemen langs het <a href='https://www.blotevoetenzeebodempad.nl/' target='_blank'>Bloten voeten Zeebodempad</a> in Kraggenburg. Daar begint je date pas echt, je kan daar ongeveer 2,5 km wandelen, maar let wel op! Dit allemaal op blote voeten, dus niet bang zijn om samen een beetje vies te worden? Dat is dit zeker te overwegen waard met je actieve date! Kortom daten in Flevoland biedt enorm veel mogelijkheden dus wacht niet langer en maak contact op de beste datingsite van de provincie!</p>",
						'img' 	=>	"flevoland"
						),
					"friesland" => array(

						'name' 	=> 	"Friesland",
						'title' 	=> 	"Dating Friesland",
						'info' 	=>	"Wist je dat de heetste meiden uit Friesland komen? Al deze vrijgezellen zijn beschikbaar voor en heerlijke spannende gratis date. Zoek je alleen een relatie, klik dan gauw op een dame die past bij jou. De meeste zijn op dit moment online en willen net als jij een gratis date! Op deze gratis datingsite is er genoeg keuze dus vind snel jouw date! Zoek bijvoorbeeld een date in Leeuwarden of een afspraakje in Drachten.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Friesland?</h3><hr><p>Nadat jij het eerste contact hebt gelegd op deze gratis dating site is het tijd om de eerste date te hebben. Dan komt gelijk de vraag waar ga je op date in Friesland? Wij geven jou hier een aantal tips om succesvol te daten in Friesland. Hier is zoveel te bezichtigen dat je aan 1 date waarschijnlijk onmogelijk genoeg hebt. Van actieve dates tot ontspannen dates in Friesland kun je al deze dates vinden.</p><h4>Waar kan je het beste daten in Friesland</h4><p>Wil je een actieve date dan is het zeker aan te raden om jouw date mee te nemen naar <a href='https://thialf.nl/' target='_blank'>Thialf</a>. Daar, in Heerenveen, kunnen jullie samen een aantal rondjes schaatsen. Wat is er nu mooier dan een rondje schaatsen en jouw date in je armen te laten vallen als ze niet rechtop kan blijven staan! Toch geen held op schaatsen? Dan kan je lekker uitwaaien op de Wadden. Een dagje Wadden is heerlijk vertoeven, het is wel raadsaam om met het bootje te gaan anders is het moeilijk om terecht te komen op de eilanden. Op die plek kan je heerlijk eten of drinken en leuke dingen te bekijken. Misschien zie je zelfs wel een zeehondje die op het strand lekker ligt te zonnen. Zeg nou zelf, als je date dit ziet zitten dan heb je haar toch voor het leven?</p><h4>Dating Friesland</h4><p>Maar er is nog veel meer te doen in Friesland. Zo heb je ook de <a href='https://www.aquazoo.nl/' target='_blank'>Aquazoo</a>, in de zoo kun je allerlei soorten dieren bekijken. Het is met recht  het leukste dierenpark van Friesland. Om je date niet saai te laten verlopen is dit een hele goede optie. Het is weer eens wat anders dan een saaie standaard date waarbij je naar de bios gaat en er een stilte valt omdat je in de film zit. In Friesland zijn meer dan 10.000 vrouwen die wachten op de man van hun dromen. Zij wachten op deze gratis dating site tot ze worden meevraagt op een spannende date. Laat jij jouw date nu nog wachten? Kijk snel tussen de Dating Friesland. Zoek jouw liefde op en vraag haar mee een dagje uit te gaan. Met de gegeven dating tips ben je verzekerd van een zeer leuke en spannende date.</p>",
						'img' 	=>	"friesland"
						),
					"gelderland" => array(

						'name' 	=> 	"Gelderland",
						'title' 	=> 	"Dating Gelderland",
						'info' 	=>	"In Gelderland wonen niet alleen boerenvrouwtjes. Dit is een provincie met volop keuze naar leuke single dames. Zij die niet alleen voor een praatje gaan, maar snel willen daten en soms niets meer willen dan spannende afspraakjes. Blijf niet wachten en zoek snel een date in Gelderland. Spreek je droomvrouw aan en wie weet vind jij jouw liefje voor het leven, bijvoorbeeld tijdens een gezellige date in Arnhem.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Gelderland?</h3><hr><p>Oproepjes Nederland heeft aanbod genoeg en is volgens velen daarom de beste datingsite van de provincie. Een date in Gelderland is dan ook zo gevonden maar hoe verder? Waar kan je nu goed daten in Gelderland? Hier vind je handige dating tips om van jou date een succes te maken. In Gelderland weet je zeker dat je een leuke tijd zal hebben met je date. Gelderland heeft zoveel te bezichtigen waardoor afspraakjes maken erg makkelijk is. Zoveel dat je aan een dagje daten niet genoeg hebt en jullie gemakkelijk meerdere afspraakjes kunnen hebben. Hieronder staan een aantal voorbeelden van plekken en activiteiten die daten in Gelderland tot een succes zullen maken.</p><h4>Waar kan je het beste daten in Gelderland</h4><p>In Gelderland kan je de <a href='https://www.visitveluwe.nl/' targat='_blank'>Veluwe</a> bezoeken met het bijbehorende museum. Maar er zijn zoveel leuke uitstapjes in Gelderland, dat jouw date zeer interessant kan worden. Als je dan toch kiest om in Gelderland een date mee te nemen, is het zeker aan te raden om langs het <a href='https://www.paleishetloo.nl/' target='_blank'>Paleis het Loo</a> te gaan. Dit is heel bijzonder om te zien en sinds 1984 is dit pand opengesteld aan het publiek. Zo’n koninklijk dagje uit naar het paleis zal zeker niet gaan vervelen. Toch meer passie voor lekker eten en een overheerlijk wijntje? Dan is een bezoekje aan <a href='http://www.wijnmuseum.nl' target='_blank'>het Nederlandse Wijnmuseum</a> een must om jouw date mee naartoe te nemen, ontdek hier de wijnculturen, je kan hier heerlijke wijnen proeven en de historische kelders bekijken en verkennen. Gegarandeerd een hartverwarmend uitje gedurende jullie date.</p><h4>Dating Gelderland</h4><p>In Gelderland zijn veel single vrouwen die nog steeds geen droompartner hebben gevonden, wordt jij deze droomman? En neem jij ze mee? Wil je toch een stapje terug doen en de date van je dromen meenemen naar een rustige plek, dan heb je nog een groot bos rondom Apeldoorn. Daar kan je urenlang wandelen en samen op een bankje zitten en even pauze te houden. Als je jouw date een romantisch sfeertje wilt geven, neem je een kleedje mee en wat lekkers om ergens in het bos te genieten van de natuur en vogels die je om je heen hoort fluiten, misschien is er zelfs wel een hertje te vinden of een wild zwijntje met haar jongen. Gebruik deze handige dating tips om succes te hebben op jouw date en te bewijzen dat dit de beste datingsite van de provincie is.</p>",
						'img' 	=>	"gelderland"
						),
					"groningen" => array(

						'name' 	=> 	"Groningen",
						'title' 	=> 	"Dating Groningen",
						'info' 	=>	"De knappe single dames op deze pagina zoeken een date in Groningen met jou! Zoek je een relatie of juist een spannend afspraakje, kijk snel wie jij mee uit wil vragen. Ze houden niet van urenlang chatten en willen snel daten. Want deze singles zoeken een lieve man voor de toekomst of een leuk avontuurtje. Wil jij daten in Groningen of een leuke ontmoeteing in Hoogezand zoek dan in Dating Groningen.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Groningen?</h3><hr><p>In Groningen zijn meer dan 10.000 singles die wachten op hun ultieme date? In Groningen is het 'name'lijk zo dat er meer vrouwen dan mannen wonen. Zij willen heel graag meegenomen worden om een avondje te stappen of gewoon voor een gezellige wandeling. Als jij de eerste contacten hebt gelegd en met iemand klikt kan het daten in Groningen echt beginnen. Dan wil je natuurlijk jouw date meenemen naar iets waar je beide plezier van hebt en wat de ultieme date moet worden. In Groningen is ontzettend veel te doen dus keuze genoeg.</p><h4>Waar kan je het beste daten in Groningen</h4><p>Om te beginnen kan jij je date meenemen naar <a href='https://www.groningermuseum.nl/' target='_blank'>het Groninger museum</a> of misschien een wandeling door het park. Romantisch de natuur in met een picknick gezellig op een kleedje is altijd een goed idee. Wil je het spannender maken, dan huur je een bootje en kan je heel veel meer bekijken in de natuur. Komt je date niet uit Groningen maar wil je toch de stad bezoeken of gewoon een afspraakje maakt op neutraal terrein. Ook kun je in Groningen ook genieten van het nachtleven, er zijn ontzettend veel cafeetjes en restaurantjes om te kunnen daten.</p><h4>Dating Groningen</h4><p>Je kunt in Groningen ook samen het symbool van Groningen bezoeken en samen de uitdaging aan gaan om 251 treden te <a href='https://toerisme.groningen.nl/over-groningen/stad-groningen/martinitoren/beklimming-van-de-martinitoren' target='_blank'>beklimmen van de d’ Olle Grieze</a>. Dit vergt wat conditie maar het uitzicht is prachtig om te zien. Om bij te komen kan je jouw date in je armen laten vallen om bij te komen en daarboven even lekker zitten om bij te komen onder het genot van een drankje, die je dan zelf mee hebt genomen. Kortom in Groningen is er altijd wat te doen en heb je zoveel kleine historische dorpjes waar je van alles kunt bezichtigen, je laat jouw date toch ook niet wachten tot de kans verkeken is bij een ander? Zoek tussen de Dating Groningen en grijp je kans!</p>",
						'img' 	=>	"groningen"
						),
					"limburg" => array(

						'name' 	=> 	"Limburg",
						'title' 	=> 	"Dating Limburg",
						'info' 	=>	"In Limburg weten ze wel wat feest vieren is. Het is er altijd gezellig dus ideaal voor bijvoorbeeld een leuk afspraakje in Maastricht of een spannende date in Venlo. Loop jij niet weg voor een eerste gratis date en wil jij de vrouw van jouw dromen vinden? Kijk dan niet verder! Deze singles uit Limburg zoeken allemaal een man om te daten dus ga snel op zoek op deze pagina als jij uit Limburg komt.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Limburg?</h3><hr><p>Dating Limburg is ondertussen een begrip geworden onder de inwoners van deze mooie provincie. Online daten is steeds normaler geworden en er zijn nog steeds meer dan 10.000 singles die een date in Limburg zoeken. Op deze gratis datingsite staat tussen de Dating het grootste aanbod. Veel van deze dames hebben nog geen ware Jacob gevonden, laat jij jouw date tot een hoogtepunt brengen? Daten in Limburg biedt zoveel opties omdat er zoveel leuke activiteiten en plekken zijn waar jouw date kan doorgaan. Een succesvolle date in Limburg zul je bijna met zekerheid hebben.</p><h4>Waar kan je het beste daten in Limburg</h4><p>Struin samen met jouw droomdate door de <a href='https://kasteeltuinen.nl/nl/' target='_blank'>kasteeltuinen van Arcen</a>, er is niks romantischer dan hand in hand te lopen en als een prins en prinses op een hoffelijke manier te genieten van de prachtige omgeving. Wil je het rustiger doen dan kan je samen genieten van een rondvaart over de Maas. Neem een rugzakje mee met wat lekkers of misschien wel een flesje wijn en geniet van de omgeving. Zo kan je daarna je date in Limburg altijd afsluiten om nog ergens lekker te gaan eten. Er is zeker nog meer te doen, zo kan je de liefde voor wijn delen met je date en naar de <a href='https://wijngaardmartinus.nl/' target='_blank'>wijnproeverij Sint-Martinus</a> gaan. Daar heb je de keuze uit verschillende wijnen van zware wijn tot een lekker soepel en fruitig wijntje. Een lekker stukje kaas bij een wijntje doet wonderen om het nog aange'name'r te maken met jouw perfecte date.</p><h4>Dating Limburg</h4><p>Je kan er natuurlijk ook voor kiezen om in Valkenburg rond te wandelen. Valkenburg is een eeuwenoude stad waar je nog echte grotten hebt. Daten in Limburg en helemaal in een mooie plaats als Valkenburg zal jouw date tot een succes maken. Je kan hier samen met een gids in groepsverband een wandeling maken door de  <a href='https://grottenvanvalkenburg.nl/nl/home' target='_blank'>grotten van Valkenburg</a>. Trek wel iets warms aan, want het is er frisjes en soms erg koud onder de grond. Na een dagje struinen door de stad Valkenburg met jouw droom vrouw weet je zeker dat ze niks anders wilt dan op een tweede date, je hebt haar plezier laten hebben met een heerlijke dag die echt de moeite waard is om nog eens een tweede keer te bezoeken. Dating Limburg heeft zoveel mogelijkheden dat jij het met onze tips tot iets moois kan maken. Kijk bij de Dating Limburg voor jouw droomvrouw.</p>",
						'img' 	=>	"limburg"
						),
					"noord-brabant" => array(

						'name' 	=> 	"Noord-Brabant",
						'title' 	=> 	"Dating Noord-Brabant",
						'info' 	=>	"Op deze pagina vind je alle contactadvertenties van Noord-Brabant. Neem jij een van deze dames mee voor een ultieme date in Eindhoven? In Brabant brand er altijd licht dus ook een late afspraakje in Breda is met een van de singles op deze pagina gemakkelijk te regelen. Waar wacht je nog op, ze zijn online en wachten op een date bij jou in de buurt! Stuur haar een gratus bericht en regel snel een date in Noord-Brabant.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Noord-Brabant?</h3><hr><p>Na tussen de Dating Noord-Brabant je droomvrouw te hebben gevonden wil jij een ook een droomdate. Wil je weten waar je jouw droomdate in Noord-Brabant heen kan nemen? Dan hebben we hier een paar leuke dating tips om leuke afspraakjes te hebben met je contacten naar keuze. Zo heb je 'name'lijk safaripark Beekse Bergen of een gezellig dagje ’s Hertogenbosch om te winkelen. Maar ook de Efteling is de aanrader om eens te bezoeken. Wil jij er met jouw nieuwe date een speciale dag van maken? Dan is een dag in de Efteling de perfecte date. Hier kan je lekker wandelen in het sprookjesachtige bos, waar rustgevende muziek en de romantische sfeer je date kleur geeft</p><h4>Waar kan je het beste daten in Noord-Brabant</h4><p>In de <a href='https://www.efteling.com/nl' target='_blank'>Efteling</a> kunnen jullie een lekker ijsje kopen of een frietje halen, maar ook zeker samen met jouw date een poging wagen de achtbaan in te gaan of zelfs op hele grote hoogte over heel de Efteling te kijken. Dit is prachtig om te zien en hier kan je samen met jou date een hele dag vertoeven. Hierbij weet je zeker dat dit een geslaagder dag zal worden. Wil je het iets rustigers doen maar toch een safari park bezoeken? Dan heb je ook <a href='https://www.beeksebergen.nl/' target='_blank'>Beekse Bergen</a>, waar je de wilde dieren kan bezoeken en met de auto door het park mag rijden, wil jij je date dicht tegen je aan houden omdat ze het griezelig vind dat de leeuwen los rondlopen? Dan moet je haar zeker mee nemen naar safaripark Beekse Bergen.</p><h4>Dating Noord-Brabant</h4><p>In Noord-Brabant zijn meer dan 10.000 dames nog alleenstaand en single en de meeste Dating staan hier op deze gratis datingsite. Deze dames willen graag daten in Noord-Brabant en samen met een leuke man aan hun zijde ontdekken wat de provincie te bieden heeft. Neem jij haar mee naar een safaripark of de Efteling, of wil je misschien gewoon de stad van Breda bezoeken. In <a href='https://vvvbreda.nl/' target='_blank'>Breda</a> is ontzettend veel horeca en daar ben je altijd verzekerd van lekker eten. Er zijn een tal van restaurants met keuze uit Spaans, Frans Japans of zelfs Turks eten. Zo heb je keuze genoeg voor jouw afspraakjes, zelfs de ouderwetse frietzaken zijn er nog aanwezig, waar je een heerlijke puntzak friet kunt halen, dat doet het toch altijd goed bij de vrouw. Je hebt zo zeker een eerste goede match met jouw vrouw naar keuze.</p>",
						'img' 	=>	"noord-brabant"
						),
					"noord-holland" => array(

						'name' 	=> 	"Noord-Holland",
						'title' 	=> 	"Dating Noord-Holland",
						'info' 	=>	"Voor een leuke date in Noord-Holland is er voor iedereen wat te vinden. Alle singles van Noord-Holland zoeken hier contact dus stuur ze snel een gratis bericht en meld je aan om haar reactie te kunnen ontvangen. Zoek je een gezellige date in Amsterdam of wil je liever een afspraakje in Haarlem plannen. Begin hier met de eerste stap, klik op Dating Noord-Holland en zoek jouw date!",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Noord-Holland?</h3><hr><p>Wat er te doen is op een date in Noord-Holland? Genoeg! Oproepjes Nederland heeft als beste datingsite hier een aantal dating tips op een rijtje gezet. Wil je jouw droom date mee nemen naar een romantisch strand, dan is <a href='https://www.vvvzandvoort.nl/zien-en-doen/' target='_blank'>Zandvoort</a> de plek om te daten in Noord-Holland. Daar kan je samen een bezoekje brengen aan het prachtige strand. De duinen waar je heerlijk doorheen kan wandelen, je kan er uren genot hebben. Wel is het aan te raden om zelf wat eten en drinken mee te nemen zodat je onderweg even kan bijkomen met je date en een gezellig praatje kan maken terwijl jullie wat eten nuttigen. In Zandvoort heb je natuurlijk ook veel strandtenten waar je een lekker visje kan happen. Houden jullie niet van vis? Dan is er genoeg anders om eens binnen te lopen. Er zijn genoeg restaurants waar ze ook vlees en vegetarische gerechten serveren.</p><h4>Waar kan je het beste daten in Noord-Holland</h4><p>Als je dan toch kiest voor jouw date in Noord-Holland, omdat jullie er beide vandaan komen of gewoon even weg willen zijn uit eigen stad, dan is de dating Amsterdam ook zeker een aanrader. Daten in Amsterdam heeft 'name'lijk zoveel te bieden. Met verschillende culturen, veel museums en ook heel veel historie die je kan bekijken. Het <a href='https://www.rijksmuseum.nl/' target='_blank'>Rijksmuseum</a> heeft zoveel mooie schilderijen en beelden waar jij met je date over kan kletsen tijdens het daten in Amsterdam. Of wat dacht je van de Lift Experience waar jij met je date over heel Amsterdam kan kijken. Deze bijzondere date in Amsterdam zal je dan ook om nooit te vergeten zijn. Met dating Amsterdam weet je zeker dat er een vervolgdate zal komen. Amsterdam heeft genoeg vrijgezellen die voor zo een leuke date openstaan.</p><h4>Dating Noord-Holland</h4><p>Dating Noord-Holland, daar lopen nog teveel single vrouwen rond die hun aanstaande date niet hebben gevonden. Zij zoeken de man die hun een mooie toekomst kan geven, laat jij die kans lopen? Kijk tussen de Dating Noord-Holland en vraag vandaag nog de vrouw van je dromen mee op date. Al is het voor een dagje <a href='https://www.texel.net/nl/' target='_blank'>Texel</a> om even uit te waaien. Tijdens de overtocht naar Texel ontdek je samen met jouw date de mooiste plekjes van het eiland. Een bezoekje aan het strand van Texel is zeer zeker een must om te zien. Hiermee creëer je met jouw droom date een warm vakantiegevoel. Daten in Noord-Holland heeft genoeg opties dus wacht niet langer en zet de eerste stap op de beste datingsite van Nederland!</p>",
						'img' 	=>	"noord-holland"
						),
					"overijssel" => array(

						'name' 	=> 	"Overijssel",
						'title' 	=> 	"Dating Overijssel",
						'info' 	=>	"Overijssel is de provincie met de meest opwindende vrouwen van Nederland. Heel veel vrijgezellen zoeken een leuke partner of een leuke one-night-stand. Van daten in Zwolle tot daten in Deventer het eerste contact begint hier. Nodig jij je nieuwe vlam uit voor een lekker drankje en een hapje? Klik op Dating Noord-Holland en maak jouw keuze om gratis berichten naar te sturen. Wie weet zit deze vrouw snel naast jou op de bank.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Overijssel?</h3><hr><p>Het begint met het vinden van je match tussen de Dating Overijssel. Na eerst het contact gelegd te hebben via de gratis chat komt het moment dat jullie gaan daten in Overijssel. Dating Overijssel heeft van alles te doen om romantisch te kunnen daten. Als je een leuke single aan de haak hebt geslagen wil je haar natuurlijk naar een van de leukste plekjes in Overijssel nemen. Als dat zo is dan moet je natuurlijk ook wel weten wat er te doen is. Gelukkig heeft Overijssel genoeg te bieden, je kunt er museums bezoeken met prachtige kunstwerken of historische onderwerpen. Zo kan je haar meenemen en een ritje maken door de grachten van <a href='https://www.giethoorn.com/' target='_blank'>Giethoorn</a>, je vaart hier met een bootje langs de kleine grachtjes en rustieke huisjes en tuinen. Waar je in een prachtig sprookje bent belandt en een spannende maar ook zeer zeker romantische date zal hebben.</p><h4>Waar kan je het beste daten in Overijssel</h4><p>Heb je zin om je date mee te nemen naar een attractiepark of wil je misschien er gelijk twee dagen aan vast plakken? Dan is het park Slagharen zeker een aanrader. Hier kan je een huisje huren voor twee personen of meer en overnachten. Op het park is er genoeg te doen, je kan er shows bekijken, zoals een cowboyshow met paarden. Ook kan je in de kabelbaan over het park en alles van bovenaf bekijken. In het park Slagharen heb je zelfs een zwembad, als je dan toch gaat daten in Overijssel dan is <a href='https://www.slagharen.com/' target='_blank'>Slagharen</a> een goede optie. Na een lange dag genieten neem je beide een verfrissende duik in het zwembad op het park. Dan is je date in Overijssel toch helemaal geslaagd?</p><h4>Dating Overijssel</h4><p>Er zijn in Overijssel teveel single vrouwen die nog geen leuke partner hebben gevonden. Daarom is online dating Overijssel de manier om je droomvrouw te vinden. Jouw date maak je ook blij door haar mee te nemen op een dagje shoppen in Zwolle of Enschede. In deze steden valt 'name'lijk ontzettend veel te doen en de echte shopaholics kunnen helemaal los gaan. In de mooie winkelstraten is van alles te zien en te koop dus ook jij kan je hart luchten. Natuurlijk kan jij ook gewoon andere steden bezoeken met jouw date. Vrouwen zijn daar gek op en je weet hierbij zeker dat de date geslaagd zal zijn. Na al dat shoppen gezellig kletsen onder het genot van een drankje is in alle steden van de provincie een must. Daten in Overijssel was nog nooit zo makkelijk dus pak je kans en kijk tussen de Dating!</p>",
						'img' 	=>	"overijssel"
						),
					"utrecht" => array(

						'name' 	=> 	"Utrecht",
						'title' 	=> 	"Dating Utrecht",
						'info' 	=>	"In Utrecht wonen heel veel mooie vrouwen die nog single zijn. Gratis daten in Utrecht is een begrip en er zijn dan ook genoeg leuke restaurants om gezellig te daten. Op deze gratis datingsite vind je alle contactadvertenties van Utrecht van vrouwen die bijvoorbeeld een afspraakje in Amersfoort zoeken. Klik op Dating Utrecht en start jouw dating avontuur.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Utrecht?</h3><hr><p>Online dating Utrecht heeft ontzettend veel te bieden en op deze gratis dating site helpen wij jou daarbij. Kijk tussen de Dating Utrecht en kies je match. In de contact oproepjes geven de meeste singles duidelijk aan wat zij zoeken. Hierdoor kan jij snel zien of jullie een match zijn. Daarna kan het daten in Utrecht zeker beginnen. Utrecht is naast een provincie ook een bekende stad, waar je jouw date mee naartoe kan nemen. Utrecht is een stad die je niet mag overslaan als het gaat om de beste date van Nederland. In Utrecht kan je samen 'name'lijk zoveel ondernemen, dat wordt gegarandeerd de leukste date die je ooit hebt meegemaakt. Heb jij al de kriebels in je buik omdat je het spannend vind waar je jouw date in Utrecht voor zal uitnodigen? Hier hebben wij wat activiteiten op een rijtje gezet waardoor je date zeker zal slagen.</p><h4>Waar kan je het beste daten in Utrecht</h4><p>Jouw date in Utrecht kan je bijvoorbeeld meenemen naar <a href='https://www.ouwehand.nl/' target='_blank'>Ouwehands Dierenpark</a> in Rhenen. Dit dierenpark dat al jaren bestaat is altijd heel gezellig. Het is niet speciaal voor kinderen dus kan jij jouw date verzekeren van een leuke dag. In Ouwehands dierenpark kan je 'name'lijk aapjes bekijken, ijsberen bezichtigen en leuke shows zien of misschien gewoon een gezellige dagje wandelen door het park. Wil jij je eerste date romantisch maken? Dan is het sprookjes kasteel de Haar zeker goud waard om je romantische date mee naartoe te nemen. Het <a href='https://www.kasteeldehaar.nl/' target='_blank'>landgoed van de Haar</a> is een sprookjesachtige verschijning waar je op het gemak kunt wandelen. Met een gids die alles uitlegt over de historie van dit prachtige Engelse park is het misschien nog beter. Zo weet je zeker dat daten in Utrecht een succes zal worden!</p><h4>Dating Utrecht</h4><p>In Utrecht en omgeving zijn meer single vrouwen dan in heel Nederland. Deze singles hebben nog steeds niet de juiste mannen gevonden. Zij zoeken dus nog een gezellige man die hun dromen waarmaken. Neem jij jouw date mee naar de <a href='https://www.domtoren.nl/nl' target='_blank'>Domtoren</a>? Iets wat je beslist niet mag missen om te bekijken en beklimmen in Utrecht? Deze kerktoren is de hoogste kerktoren van Nederland en je zal hiermee een zeer actieve date hebben. Het is heerlijk om dit samen te ondernemen. Nadat jullie beide uitgeput raken van het beklimmen van deze toren, is er beneden op het plein genoeg te eten en drinken. De stad is bomvol met kleine restaurantjes en eetcafeetjes om heerlijk te kunnen uitrusten en even wat kan eten. Romantischer dan daten in Utrecht is er bijna niet dus kijk snel tussen de Dating Utrecht op deze gratis dating site.</p>",
						'img' 	=>	"utrecht"
						),
					"zeeland" => array(

						'name' 	=> 	"Zeeland",
						'title' 	=> 	"Dating Zeeland",
						'info' 	=>	"Zeeland de parel van het zuiden. Hier wonen de meest sexy singles, allemaal op zoek naar een leuke date in Terneuzen of een gezellig afspraakje in Middelburg. Wil jij met jouw date over de boulevard van Zeeland wandelen tijdens jullie eerste date? Klik op Dating Zeeland daten en je bent verzekerd van spannende contact met een leuke vrouw in Zeeland. Met deze gratis datingsite is succes bijna gegarandeerd.",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Zeeland?</h3><hr><p>Niet zo heel bekend in Zeeland? In Zeeland is zeer zeker veel te bekijken, zo kan je jouw date meenemen naar Neeltje Jans, of heerlijk wandelen over de boulevard van Vlissingen. Heb je jouw single of date op deze gratis datingsite leren kennen in Zeeland of omgeving? Dan weet je zeker dat jou date zeer geslaagd zal zijn als jullie ook gaan daten in Zeeland. Tussen de Dating Zeeland staan genoeg dames waarvan er vast één voldoet aan jouw wensen. Zoek snel je match en kijk hieronder wat jullie allemaal voor leuks kunnen doen op jullie date in Zeeland.</p><h4>Waar kan je het beste daten in Zeeland</h4><p>In Zeeland kan je bijvoorbeeld samen met je date de Abdijtoren beklimmen <a href='http://www.langejanmiddelburg.nl/' target='_blank'>De Lange Jan</a> in Middelburg. Ben je eenmaal bovenaan gekomen met je date? Dan heb je daar een prachtig uitzicht over de stad Middelburg. Daarna mogen jullie natuurlijk jezelf belonen op een lekker hapje of drankje in de stad. Die stad heeft talloze restaurantjes en je kunt er heerlijk op het terras zitten. Heb je zin om even samen met je date uit te waaien? Dan is het <a href='https://www.neeltjejans.nl/' target='_blank'>Deltapark Neeltje Jans</a> een bezoekje waard. Hier kan je de historie bekijken van de deltawerken van Zeeland. Een bezoekje aan het waterpark is zeker  de moeite waard. Je kan je jezelf met je date verdiepen in de walviswereld of je kiest met je date om een rondvaart te nemen over de Oosterschelde. Met die activiteit heb je gegarandeerd een bijzondere ervaring en is misschien beste manier om te daten in Zeeland.</p><h4>Dating Zeeland</h4><p>In Zeeland zijn ontzettend veel single vrouwen die nog nooit mee hebben gemaakt dat zij worden meegevraagd om te daten in Zeeland. Dit komt omdat ze gewoonweg niet gevraagd worden om Zeeland te ontdekken. Zeeland is zelfs gekozen als de romantische stad van Nederland. Daardoor ben je verzekerd van een geslaagde date met je single vrouw. In Zeeland kan je zelfs een reisje maken met de <a href='https://www.destoomtrein.nl/cms/' target='_blank'>stoomtrein Goes-Borsele</a>. Hiermee wanen jullie je in de tijd van de vorige eeuw met al zijn romantiek. Zo kan je bijvoorbeeld met de stoomtrein door de polders of de verschillende fruitboomgaarden gaan en zie je hoe prachtig Zeeland wel niet is. Daarna sluiten jullie de date af met een lekker hapje of drankje. Dating Zeeland heeft zoveel te bieden dat je date in Zeeland wel moet slagen. Kijk snel tussen de Dating Zeeland en zoek snel je date op deze gratis datingsite.</p>",
						'img' 	=>	"zeeland"
				
						),
					"zuid-holland" => array(

						'name' 	=> 	"Zuid-Holland",
						'title' 	=> 	"Dating Zuid-Holland",
						'info' 	=>	"Op deze pagina vind je alle vrouwen die willen daten in Zuid-Holland. Zoek jij een date in Den Haag of wil jij gratis daten in Rotterdam? Dan ben jij op deze pagina op de goede plek. Hier vind je alle contactadvertenties van Zuid-Holland dus ook voor een date in Zoetermeer kan je er terecht. Een aantal vrijgezellen zijn op dit moment online, nodig ze vanavond nog uit!",
						'intro' 	=>  "Hier komt de introductie van de pagina",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Zuid-Holland?</h3><hr><p>Zoek tussen de Dating Zuid-Holland naar jouw match en vraag haar mee uit. Als jij die date hebt gescoord kan jij hier lezen hoe jij de eerste date in Zuid-Holland tot een succes maakt. Dating Den Haag biedt opties om jouw date een onvergetelijke dag te laten beleven. <a href='https://scheveningen.com/nl/' target='_blank'>Scheveningen</a> bijvoorbeeld, met de prachtige boulevard waar je uren over kunt wandelen. Je kan er allerlei winkeltjes bekijken of er leuke souvenirs en kleren kopen. Wil jij jouw date laten zien dat niets te gek is! In Scheveningen, kan je zelfs even over het strand wandelen of de pier bezoeken en daar een drankje nuttigen. In Scheveningen is het altijd druk en super gezellig, er is altijd wat te doen. Je zou er zelfs je date mee kunnen nemen naar het <a href='https://www.hollandcasino.nl/en/vestigingen/scheveningen' target='_blank'>casino</a>, mochten jullie een gokje willen wagen. Dating Den Haag bied genoeg opties dus wacht niet langer en gebruik de tips.</p><h4>Waar kan je het beste daten in Zuid-Holland</h4><p>Toch geen Scheveningen? Dan is Rotterdam bij uitstek de stad om eens te bezichtigen. Dating Rotterdam biedt genoeg opties voor een leuke date. In Rotterdam kan je 'name'lijk heerlijk wandelen in de stad die erg groot is en voor ieder wat wils. Ook heb je in Rotterdam het <a href='https://www.wereldmuseum.nl/' target='_blank'>Wereldmuseum</a> die een zeer gevarieerde tentoonstellingen heeft met een vaste collectie. Dit museum is de perfecte plek om samen verschillende zalen te bezichtigen en te eindigen in de omliggende restaurants. In Rotterdam zijn meer dan 10.000 single vrouwen nog alleen die de avonden en weekenden alleen doorbrengen. Dit komt omdat ze nog steeds niet mee gevraagd zijn op een spannende date in Zuid-Holland. Deze vrouwen wachten tot ze gevraagd worden door jou! Blijf jij wachten of ga jij deze vrouwen helpen met dating Rotterdam? </p><h4>Dating Zuid-Holland</h4><p>Waar wacht je nog op, zoek tussen de Dating Zuid-Holland naar de vrouw van je toekomst. Vraag haar mee uit om te daten in Zuid-Holland en jouw date heeft zeker een goede afloop. Wil je verzekerd zijn van de perfecte date in Zuid -Holland, dan heb je aan deze dating tips genoeg. Wie weet is deze date zo goed verlopen dat de tweede er snel opvolgt. Ga je dan weer daten in Zuid-Holland dan kan jij een andere dating tip gebruiken. Voor je het weet, heb je een relatie voor het leven hebt. Rotterdam staat bekend om de meeste succesvolle dates met de langste relaties. Zoek tussen de Dating Zuid-Holland jouw match om dit te bevestigen.</p>",
						'img' 	=>	"zuid-holland"
						)
					);
?>